#!/usr/bin/env bash
#Displaying numbers from 1 to 100 but FizzBuzz if it is a multiple of 3 and 5, Fizz if only a multiple of 3, and Buzz if only a multiple of 5

for (( i=1; i<=100; i++ )) do

	if (( i % 3 == 0 && i % 5 == 0 )); then

		echo "FizzBuzz"

	elif (( i % 3 == 0 )); then

		echo "Fizz"

	elif (( i % 5 == 0 )); then

		echo "Buzz"

	else

		echo "$i"
	fi

done
