#!/usr/bin/env bash
#Displaying bad luck on 4th iteration and displaying good luck on the 8th. Otherwise it is Best School
i=1
while ((i<=10))
do

if((i==4))
then
echo "bad luck"

elif((i==8))
then
echo "good luck"

else
echo "Best School"
fi

((i++))

done
