#!/usr/bin/env bash
#Displaying information about a file

File=school

if [ -f "$File" ]; then

	echo "school file exists"

	if [ ! -s "$File" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "$File" ]; then
		echo "school is a regular file"
	fi

elif [ -d "$File" ]; then

	echo "school file exists"

else
	echo "school file does not exist"

fi
