#!/usr/bin/env bash
#Displaying information about a file
file=school

if [ -f "$file" ]; then

echo "school file exists"

if [ -e "$file"]; then
echo "school file is empty"
else
echo "school file is not empty"
fi

if [ -f "$file" ]; then
echo "school is a regular file"
fi

else
echo "school file does not exist"
fi
