#!/usr/bin/env bash
#Displaying information about a file

File=school

if [ -f "$File" ]; then

	echo "school file exists"

	if [ -e "$File" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "$File" ]; then
		echo "school is a regular file"
	fi

else
	echo "school file does not exist"

fi
