#!/usr/bin/env bash
#Displaying To infinity and beyond infinitely but with I am invincible when receiving the SIGTERM signal

handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

trap 'handle_sigterm' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
