#!/usr/bin/env bash
#Displaying To infinity and beyond infinitely but with I am invincible when receiving the SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
